[book]
authors = [
    "shiva.patt",
    "lylythechosenone",
    "flyingcakes85",
    "mkuja"
]
language = "en"
multilingual = false
src = "src"
title = "The Paxy Book"

[output.html]
theme = "./theme"
